version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/node_modules
hooks:
  BeforeInstall:
    - location: scripts/stop-server.sh
      timeout: 300
      runas: ec2-user
  AfterInstall:
    - location: scripts/start-sever.sh
      timeout: 300
      runas: ec2-user